<?php

return [
    'assistant_name' => 'Sherehe AI Assistant',
    'assistant_badge' => 'Rule-based AI',
    'disclaimer' => 'You are chatting with a rule-based AI assistant. Responses are automated and may not always be perfect.',
    'quick_replies' => [
        'How do I create an event?',
        'I did not receive OTP',
        'How does QR scanning work?',
        'How do I send invitations?',
        'Payment failed',
        'How do I contact support?',
    ],
    'fallback' => [
        'answer' => 'I did not fully understand that yet. Try one of these: event creation, OTP help, payments, QR scanning, invitations, or support contact.',
        'follow_ups' => [
            'How do I create an event?',
            'I did not receive OTP',
            'How do I contact support?',
        ],
    ],
    'knowledge_base' => [
        [
            'id' => 'create_event',
            'title' => 'Create a new event',
            'answer' => 'Go to Home, tap the center scanner/create button, then choose event setup. Fill event name, date, location, category, package, and cover image, then submit.',
            'keywords' => ['create event', 'new event', 'event setup', 'start event', 'add event', 'event form'],
            'follow_ups' => ['What package should I choose?', 'How do I pay for package?', 'How do I add pledgers?'],
        ],
        [
            'id' => 'event_package',
            'title' => 'Choose event package',
            'answer' => 'Packages control SMS/WhatsApp/card limits and attendees. Pick the package based on expected guests and messaging needs before you create the event.',
            'keywords' => ['package', 'plan', 'pricing', 'event package', 'choose package', 'tiers'],
            'follow_ups' => ['How do I pay for package?', 'Can I upgrade package later?', 'What payment methods are supported?'],
        ],
        [
            'id' => 'pay_package',
            'title' => 'Pay for event package',
            'answer' => 'Open event order or payment screen, choose network (M-Pesa/Airtel/Tigo/Halo), enter phone, confirm amount, and submit. You can check payment status in event payments.',
            'keywords' => ['pay package', 'payment', 'pay event', 'checkout', 'mobile money', 'order'],
            'follow_ups' => ['Payment failed', 'Where can I see transactions?', 'What networks are supported?'],
        ],
        [
            'id' => 'payment_failed',
            'title' => 'Payment failure help',
            'answer' => 'If payment fails, verify phone format, account balance, and network selection. Retry once after a minute. If still failing, check transactions and contact support with event name and phone number used.',
            'keywords' => ['payment failed', 'failed transaction', 'declined', 'payment issue', 'not paid', 'payment error'],
            'follow_ups' => ['Where can I see transactions?', 'How do I contact support?', 'What networks are supported?'],
        ],
        [
            'id' => 'transactions',
            'title' => 'View transactions',
            'answer' => 'Go to event details and open Transactions/Payments. You will see statuses like paid, unpaid, or failed with method and amount.',
            'keywords' => ['transactions', 'payment history', 'payments list', 'receipts', 'paid status'],
            'follow_ups' => ['Payment failed', 'How do I export reports?', 'How do I contact support?'],
        ],
        [
            'id' => 'otp_not_received',
            'title' => 'OTP not received',
            'answer' => 'Wait up to 60 seconds, confirm phone number format, and retry login to trigger OTP resend. If still missing, check network signal and contact support.',
            'keywords' => ['otp', 'code not received', 'verification code', 'sms code', 'did not receive otp'],
            'follow_ups' => ['How do I login?', 'How do I contact support?', 'App is showing invalid OTP'],
        ],
        [
            'id' => 'otp_invalid',
            'title' => 'Invalid OTP',
            'answer' => 'OTP expires quickly. Request a new OTP and enter the latest one only. Avoid reusing older codes.',
            'keywords' => ['invalid otp', 'wrong otp', 'otp expired', 'verification failed', 'code invalid'],
            'follow_ups' => ['I did not receive OTP', 'How do I login?', 'How do I contact support?'],
        ],
        [
            'id' => 'login_help',
            'title' => 'Login steps',
            'answer' => 'Open app, enter phone number, tap Login, then enter OTP. After successful OTP verification, you are redirected to the dashboard.',
            'keywords' => ['login', 'sign in', 'log in', 'authenticate', 'enter phone'],
            'follow_ups' => ['I did not receive OTP', 'Invalid OTP help', 'How do I logout?'],
        ],
        [
            'id' => 'logout_help',
            'title' => 'Logout',
            'answer' => 'Go to Profile and tap Logout. This clears your session and returns you to the login screen.',
            'keywords' => ['logout', 'sign out', 'log out', 'exit account'],
            'follow_ups' => ['How do I login?', 'Delete account', 'Support contact'],
        ],
        [
            'id' => 'delete_account',
            'title' => 'Delete account',
            'answer' => 'Profile has a delete account action. This is permanent and may remove your events/data. Contact support first if you need data recovery options.',
            'keywords' => ['delete account', 'remove account', 'close account', 'erase profile'],
            'follow_ups' => ['How do I contact support?', 'How do I logout?', 'Can I recover my data?'],
        ],
        [
            'id' => 'add_pledger',
            'title' => 'Add pledgers',
            'answer' => 'Open event, go to Pledgers, then add manually or import file. Include full name, phone, pledge amount, and optional table/category.',
            'keywords' => ['add pledger', 'guest list', 'attendee list', 'import pledgers', 'add attendee'],
            'follow_ups' => ['How do I edit pledger?', 'How do I add contribution?', 'How do I send invitation?'],
        ],
        [
            'id' => 'edit_pledger',
            'title' => 'Edit or delete pledger',
            'answer' => 'In Pledgers list, open the action menu on a person to edit details, add payment, or delete.',
            'keywords' => ['edit pledger', 'update attendee', 'delete pledger', 'remove guest'],
            'follow_ups' => ['How do I add contribution?', 'How do I send invitation?', 'How does QR check-in work?'],
        ],
        [
            'id' => 'add_contribution',
            'title' => 'Add contribution/payment',
            'answer' => 'Open a pledger record, choose Add Contribution, then provide method, amount, and transaction reference.',
            'keywords' => ['add contribution', 'pledge payment', 'record payment', 'contribution', 'add paid amount'],
            'follow_ups' => ['How do I view transactions?', 'Why card type is single/double?', 'How does QR check-in work?'],
        ],
        [
            'id' => 'send_invitation',
            'title' => 'Send invitations',
            'answer' => 'From Pledgers list, use invite action. Depending on card/ticket type, the app sends ticket, card image, named card, or link.',
            'keywords' => ['send invitation', 'invite guest', 'send card', 'send ticket', 'invitation link'],
            'follow_ups' => ['WhatsApp invitation help', 'SMS invitation help', 'QR scanning help'],
        ],
        [
            'id' => 'sms_notifications',
            'title' => 'SMS notifications',
            'answer' => 'You can send reminders and updates from event notifications. Make sure event has enough SMS balance.',
            'keywords' => ['sms', 'text message', 'bulk sms', 'send sms', 'reminder sms'],
            'follow_ups' => ['How do I top up SMS balance?', 'WhatsApp notification help', 'How do I contact support?'],
        ],
        [
            'id' => 'whatsapp_notifications',
            'title' => 'WhatsApp notifications',
            'answer' => 'Use event WhatsApp tools to send image/news messages. Ensure phone numbers are valid and include country code.',
            'keywords' => ['whatsapp', 'send whatsapp', 'news image', 'whats app', 'wa message'],
            'follow_ups' => ['SMS notification help', 'Send invitation', 'How do I contact support?'],
        ],
        [
            'id' => 'scan_qr',
            'title' => 'QR scanning and check-in',
            'answer' => 'Tap the scanner button, allow camera permission, and scan guest code. The app validates attendance and card type, then marks check-in.',
            'keywords' => ['qr', 'scan', 'scanner', 'check in', 'entry code', 'verify code'],
            'follow_ups' => ['Code already used', 'Camera permission issue', 'Single vs Double card'],
        ],
        [
            'id' => 'code_used',
            'title' => 'Code already used',
            'answer' => 'If you see already attending, the guest has already been checked in for that event or reached check-in limit for the card type.',
            'keywords' => ['already used', 'already attending', 'code used', 'duplicate scan'],
            'follow_ups' => ['Single vs Double card', 'How to verify pledge by code?', 'Contact support'],
        ],
        [
            'id' => 'single_double_card',
            'title' => 'Single vs Double card',
            'answer' => 'Single cards complete attendance in one scan. Double cards may require two scans/check-ins before attendee is marked fully attending.',
            'keywords' => ['single card', 'double card', 'card type', 'checkin count', 'card eligibility'],
            'follow_ups' => ['QR scanning help', 'Code already used', 'Pledger contributions'],
        ],
        [
            'id' => 'camera_permission',
            'title' => 'Camera permission',
            'answer' => 'If scanner is not working, allow camera access in phone settings and reopen scanner.',
            'keywords' => ['camera permission', 'scanner not working', 'camera denied', 'cannot scan'],
            'follow_ups' => ['QR scanning help', 'Code invalid help', 'Contact support'],
        ],
        [
            'id' => 'event_gallery',
            'title' => 'Event gallery',
            'answer' => 'You can upload event gallery images and links from event action gallery section, then share those assets with attendees.',
            'keywords' => ['gallery', 'upload image', 'event photos', 'share gallery', 'media'],
            'follow_ups' => ['How to send news image?', 'How to share event links?', 'Support contact'],
        ],
        [
            'id' => 'event_reports',
            'title' => 'Event report and recap',
            'answer' => 'Use Recap/Report screens to review completed events, attendance trends, and basic transaction performance.',
            'keywords' => ['report', 'recap', 'analytics', 'summary', 'event report'],
            'follow_ups' => ['View transactions', 'Pledgers list help', 'Contact support'],
        ],
        [
            'id' => 'language_help',
            'title' => 'Language support',
            'answer' => 'Sherehe supports Swahili and English communication patterns in many workflows. For wording customizations, contact support.',
            'keywords' => ['language', 'swahili', 'english', 'translate', 'lugha'],
            'follow_ups' => ['How to contact support?', 'SMS templates', 'WhatsApp templates'],
        ],
        [
            'id' => 'support_contact',
            'title' => 'Contact support',
            'answer' => 'Reach support via phone +255 712 902 927, email support@sherehe.co.tz, or website https://sherehe.co.tz. Include your event name and issue details for faster help.',
            'keywords' => ['support', 'help', 'contact', 'call', 'email', 'whatsapp support'],
            'follow_ups' => ['Call support now', 'Email support now', 'Submit feedback'],
        ],
        [
            'id' => 'submit_feedback',
            'title' => 'Submit feedback',
            'answer' => 'In Support & Help, tap Submit Feedback. Choose category (general/bug/feature/complaint), add subject and message, then submit.',
            'keywords' => ['feedback', 'bug report', 'feature request', 'complaint', 'rate app'],
            'follow_ups' => ['Where can I see my feedback history?', 'How do I contact support?', 'How to report payment issue?'],
        ],
        [
            'id' => 'feedback_history',
            'title' => 'Feedback history',
            'answer' => 'Open Support > Feedback > My History tab to view your submitted feedback records.',
            'keywords' => ['feedback history', 'my feedbacks', 'submitted feedback', 'complaint history'],
            'follow_ups' => ['Submit feedback', 'Contact support', 'Rate app'],
        ],
        [
            'id' => 'app_update',
            'title' => 'App updates',
            'answer' => 'The app can prompt for updates automatically. Update to the latest version for best stability and new features.',
            'keywords' => ['update app', 'new version', 'upgrade app', 'latest app'],
            'follow_ups' => ['Why app is slow?', 'How do I report a bug?', 'Contact support'],
        ],
        [
            'id' => 'slow_app',
            'title' => 'App performance',
            'answer' => 'If app is slow, check internet quality, close background apps, and update to latest version. Re-login can also refresh sync issues.',
            'keywords' => ['slow', 'lag', 'hanging', 'performance', 'app freeze'],
            'follow_ups' => ['App update help', 'Login help', 'Contact support'],
        ],
        [
            'id' => 'internet_issue',
            'title' => 'No internet connection',
            'answer' => 'Switch network or enable data/Wi-Fi, then retry. Most actions require active internet to sync with server.',
            'keywords' => ['no internet', 'offline', 'network error', 'connection problem', 'socketexception'],
            'follow_ups' => ['Why scanner failed?', 'Payment failed', 'Support contact'],
        ],
        [
            'id' => 'security_notice',
            'title' => 'Security and privacy',
            'answer' => 'Never share OTP or private account details with others. Use only official support channels listed in the app.',
            'keywords' => ['security', 'privacy', 'safe', 'protect account', 'otp sharing'],
            'follow_ups' => ['OTP help', 'Support contact', 'Delete account'],
        ],
    ],
];
